spring.application.name=Chat Project
spring.datasource.url=jdbc:postgresql://localhost:5432/chat
spring.datasource.username=postgres
spring.datasource.password=user1234


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true